#!/bin/bash

shopt -s checkwinsize

# shellcheck disable=SC1091
. /etc/bash_completion

# shellcheck source=gitfunctions.sh
. ~/gitfunctions.sh

# emacs
export EDITOR="emacsclient -ct -a ''"
export ESHELL=/bin/bash

PROMPT_COMMAND='LAST_EXIT=$? ; [ $LAST_EXIT == 0 ] && unset LAST_EXIT'

export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_SHOWDIRTYSTATE=true
PS1='\[\e[33m\]${DOCKER}'
PS1+='\[\e[36m\]${AWS_VAULT:+[${AWS_VAULT}]}'
PS1+='\[\e[34m\]${K8S:+[${K8S}]}'
PS1+='\[\e[35m\]($(mygitdir):$(mygitbranch))'
PS1+='\[\e[32m\]${LAST_EXIT:+\[\e[31m\]($LAST_EXIT)}$'
PS1+='\[\e[0m\] '

dir()  { ls -AlFh --color "$@"; }
dirt() { dir -rt "$@"; }
dird() { dir -d "$@"; }
rea()  { history | grep -E "${@:-}"; }
c()    { cat "$@"; }
g()    { grep -nIHE --color "$@"; }
m()    { less "$@"; }

awshell() { profile="${1:-test}"; aws-vault exec "$profile" bash; }

# snarf k8s context
if [ -f ~/.kube/config ] && test "$(command -v kubectl)" ; then
    PROMPT_COMMAND+=' ; K8S=$(grep -o "current-context.*" ~/.kube/config | cut -c18-)'
fi

# source all executable file on the form "/opt/includes/bash_local_*"
# shellcheck disable=SC1090
while read -r line
do . "$line"
done < <(find -D exec /opt/includes -type f -name "bash_local_*" -executable)
