#!/bin/bash

shopt -s checkwinsize

# shellcheck disable=SC1091
. /etc/bash_completion

# shellcheck source=gitfunctions.sh
. ~/gitfunctions.sh

# emacs
export EDITOR="emacsclient -ct -a ''"
export ESHELL=/bin/bash

PROMPT_COMMAND='LAST_EXIT=$? ; [ $LAST_EXIT == 0 ] && unset LAST_EXIT'

export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_SHOWDIRTYSTATE=true
PS1='\[\e[33m\]${DOCKER}'
PS1+='\[\e[36m\]${AWS_PROFILE:+[${AWS_PROFILE}]}'
PS1+='\[\e[35m\]($(mygitdir):$(mygitbranch))'
PS1+='\[\e[32m\]${LAST_EXIT:+\[\e[31m\]($LAST_EXIT)}$'
PS1+='\[\e[0m\] '

dir()  { ls -AlFh --color "$@"; }
dirt() { dir -rt "$@"; }
dird() { dir -d "$@"; }
rea()  { history | grep -E "${@:-}"; }
c()    { cat "$@"; }
g()    { grep -nIHE --color "$@"; }
m()    { less "$@"; }

# set up AWS and k8s if possible
unset AWS_PROFILE
if [ -f ~/.aws/config ] && grep -q "profile prod" ~/.aws/config ; then
    export AWS_PROFILE=prod
fi
if [ -f ~/.kube/config ] && test "$(command -v kubectl)" ; then
    export AWS_PROFILE
    PROMPT_COMMAND+=' ; AWS_PROFILE=$(grep -o "current-context.*" ~/.kube/config | cut -c18-)'
fi
